const DELIMITER_CHANGED = "DELIMITER_CHANGED";
const ROW_COUNT_CHANGED = "ROW_COUNT_CHANGED";
const FILTER_CHANGED = "FILTER_CHANGED";
const FILTER_UPDATE = "FILTER_UPDATE";
const FILE_DATA_CHANGED = "FILE_DATA_CHANGED";
const UPLOAD_STATUS_CHANGED = "UPLOAD_STATUS_CHANGED";
const FETCH_STATUS_CHANGED = "FETCH_STATUS_CHANGED";
const UPLOAD_FILE = "UPLOAD_FILE";
const TABLE_DATA_CHANGED = "TABLE_DATA_CHANGED";
const GET_DATA = "GET_DATA";

export {
  DELIMITER_CHANGED,
  ROW_COUNT_CHANGED,
  FILE_DATA_CHANGED,
  UPLOAD_STATUS_CHANGED,
  TABLE_DATA_CHANGED,
  FILTER_CHANGED,
  FILTER_UPDATE,
  GET_DATA,
  UPLOAD_FILE,
  FETCH_STATUS_CHANGED
};
